name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  video_player: ^2.9.5
  pedometer: ^4.0.0
  permission_handler: ^11.3.0
  connectivity_plus: ^6.1.4
  audioplayers: ^5.2.1
  flutter_secure_storage: ^9.2.4
  table_calendar: ^3.1.3
  flutter_localization: ^0.3.2
  firebase_database: ^11.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
    - assets/sounds/
